const base_url = 'http://192.169.243.70:5000/';
// const base_url = 'http://192.169.243.70:8200/';
// const base_url1 = 'http://192.168.0.116:9000/';
export const AppSettings = {
    loginUrl: base_url + 'users/admin/login',
    getCatUrl: base_url + 'cart/admin/catagiry',
    addCatUrl: base_url + 'cart/admin/insert',
    updateCat: base_url + 'cart/admin/update',
    deleteCat: base_url + 'cart/admin/delete',
    getProductUrl: base_url + 'products/getproduct?npp=10&',
    deleteSkuUrl: base_url + 'products/deletesku',
    deleteProdUrl: base_url + 'products/deleteproduct',
    updateProdUrl: base_url + 'products/updateproduct',
    insertProduct: base_url + 'products/insertproduct',
    insertSubCat: base_url + 'subcategorty/insertcategory',
    getSubCategory: base_url + 'subcategorty/getdata',
    deleteSubCat: base_url + 'subcategorty/delete',
    updateSubCat: base_url + 'subcategorty/update',
    uploadProductimg: base_url + 'products/uploadimage',
    importExcel: base_url + 'products/readExcel',
    multiproductimgUrl: base_url + 'products/getproductbyid',
    getSubCatUrl: base_url + 'products/getsubdata',
    deleteProImgUrl: base_url + 'products/deleteproductimage',
    getVendorUrl: 'http://192.168.0.116:9000/vendors',
    getVendorById: base_url + 'vendors/',
    updateVendorById: base_url + 'vendors/',
    deleteVendorById: 'http://192.168.0.116:9000/vendors/',
    getOrdersUrl: base_url + 'oders',
    getOffersUrl: base_url + 'voucher',
    postOffersUrl: base_url + 'voucher',
    getOfferbyId: base_url + 'voucher/',
    updateOfferById: base_url + 'voucher/',
    deleteOfferById: base_url + 'voucher/',
    addDeliveryUrl: base_url + 'oders/delvory',
    getDeliveryUrl: base_url + 'oders/getdelvory',
    getDeliveryById: base_url + 'oders/getbyid',
    updateDeliveryUrl: base_url + 'oders/updatedelvory',
    deleteDeliveryById: base_url + 'oders/deletedelvory',
    getCountriesUrl: base_url + 'users/location_management/countries',
    getStatesUrl: base_url + 'users/location_management/countries',
    getCityUrl: base_url + 'users/location_management/countries',
    getAreaUrl: base_url + 'users/location_management/countries',
    addLocation: base_url + 'users/add_location',
    getLocation: base_url + 'users/get_locations',
    deleteLocation: base_url + 'users/delete_location',
    // getCountries: base_url + 'location/location',
    // getCountriesUrl: base_url + 'location/getcountrys',
    // getStatesbyId: base_url + 'location/getstatus',
    termConditionsUrl: 'http://localhost:9000/terms_conditions',
    postbannersUrl: base_url + 'banners/new_banner',
    getBannerUrl: base_url + 'banners/getbanners',
    deleteBannerUrl: base_url + 'banners/delteindivisuval_banner',
    editBannerUrl: base_url + 'banners/getiddetailes',
    updatebannerUrl: base_url + 'banners/updateBanner',
    bannerPositionUrl: base_url + 'banners/getbannerpostion',
    addCityUrl: base_url + 'delivery/warehouse_coutry',
    getCitiesUrl: base_url + 'delivery/getwarehouse_country',
    getCityByID: base_url + 'delivery/getbycountryid',
    updateCityUrl: base_url + 'delivery/updatecity',
    deleteCitiesUrl: base_url + 'delivery/deletecity',
    addAreaUrl: base_url + 'delivery/warehouse_area',
    getAreasUrl: base_url + 'delivery/getallwerehousearea',

    getAreaById: base_url + 'delivery/getareabyid',

    updateAreaUrl: base_url + 'delivery/updatearea',
    deleteAreaUrl: base_url + 'delivery/deletearea',
    addwarehouseUrl: base_url + 'delivery/addarea',
    getwarehouseurl: base_url + 'delivery/getwerehousedata',

    getWarehouseById: base_url + 'delivery/getwerehousebyid',
    updatewarehouseUrl: base_url + 'delivery/updatewerehouse',
    deleteWarehouse: base_url + 'delivery/deletewerehouse',
    addslotUrl: base_url + 'delivery/insertdelivery',
    getSlotUrl: base_url + 'delivery/getdelvoryslots',
    deleteslotUrl: base_url + 'delivery/deltedate',
    termsFooterUrl: base_url + 'footer/savefooter',
    getTermsUrl: base_url + 'footer/gettermes',
    getAboutusUrl: base_url + 'footer/aboutus',
    getDeliveryInfoUrl: base_url + 'footer/DeliveryInfo',
    getPrivacyUrl: base_url + 'footer/prevent',
    updateTermsUrl: base_url + 'footer/updatefooter',
    updateAboutUsUrl: base_url + '',
    updateDeliveryInfoUrl: base_url + '',
    updatePrivacyUrl: base_url + ''
    // postDealbannersUrl: base_url + 'banners/new_banner',
    // getDealBannerUrl: base_url + 'banners/banners-list',
    // deleteDealBannerUrl: base_url + 'banners/delete_banner',
    // updateDealbannerUrl: base_url + 'banners/update_banner'
}
