const base_url = 'http://192.169.243.70:5000/';
// const base_url = 'http://192.169.243.70:8200/';
// const base_url1 = 'http://192.168.0.116:9000/';
export const AppSettings = {
    loginUrl: base_url + 'users/admin/login',
    getCatUrl: base_url + 'cart/admin/catagiry',
    addCatUrl: base_url + 'cart/admin/insert',
    updateCat: base_url + 'cart/admin/update',
    deleteCat: base_url + 'cart/admin/delete',
    getProductUrl: base_url + 'products/getproduct',
    deleteProdUrl: base_url + 'products/deleteproduct',
    updateProdUrl: base_url + 'products/updateproduct',
    insertProduct: base_url + 'products/insertproduct',
    insertSubCat: base_url + 'subcategorty/insertcategory',
    getSubCategory: base_url + 'subcategorty/getdata',
    deleteSubCat: base_url + 'subcategorty/delete',
    updateSubCat: base_url + 'subcategorty/update',
    uploadProductimg: base_url + 'products/uploadimage',
    importExcel: base_url + 'products/readExcel',
    multiproductimgUrl: base_url + 'products/getproductbyid',
    getSubCatUrl: base_url + 'products/getsubdata',
    deleteProImgUrl: base_url + 'products/deleteproductimage',
    getVendorUrl: 'http://192.168.0.116:9000/vendors',
    getVendorById: base_url + 'vendors/',
    updateVendorById: base_url + 'vendors/',
    deleteVendorById: 'http://192.168.0.116:9000/vendors/',
    getOrdersUrl: base_url + 'oders',
    getOffersUrl: 'http://192.168.0.116:9000/offers',
    postOffersUrl: 'http://192.168.0.116:9000/offers',
    getOfferbyId: 'http://192.168.0.116:9000/offers/',
    updateOfferById: 'http://192.168.0.116:9000/offers/',
    deleteOfferById: 'http://192.168.0.116:9000/offers/',
    addDeliveryUrl: base_url + 'oders/delvory',
    getDeliveryUrl: base_url + 'oders/getdelvory',
    deleteDeliveryById: base_url + 'oders/deletedelvory',
    addLocationUrl: base_url + 'location/location',
    getCountriesUrl: base_url + 'location/getcountrys',
    getStates: base_url + 'location/getstatus'
}
